### ISSUE TITLE
Mouse interactions: More differentiated operation

### ISSUE THREAD

**Issue by porg** [magic-akari/lrc-maker#111]
## Status quo

Clicking anywhere in a line selects that line.
- But does not affect playback or selection.

## Proposed changes

1. Click on leftmost empty column → Changes focus to that line, indicated by left live counter (aka "playhead").
    - Remains as it is currently.
2. Click on timecode column → Selects that line and puts playback X secs before.
    - Use case: During playback/checkup, you notice that a line is slightly off.
    - With this you get to your mistake where targeted.
    - The line above will be the currently playing one, will have the bg-color.
    - The selection is on the erroneous line, you hit SPACE at the correct time and correct your mistake.
    - Currently this is also possible with "Go back 5sec" a few times and the selection being independent from the playback. Neverthless, my proposed function would allow a slightly more "targeted" mode for corrections. Possibly a good addition.
3. Click on lyrics column → Jumps audio playback to that timestamp and selects that line.
    - As a means of navigation. "Click what you want to hear".

**Comment by magic-akari** [comment]
Double-clicking on the current line allows you to set the playback time to that specific line.
It's an undocumented feature because I have not designed the keyboard shortcuts for it yet.

**Comment by porg** [comment]
- Fine to know, that covers use case °3.
- But what about use case °2?
