### ISSUE TITLE
网易云歌曲链接无法播放

### ISSUE THREAD

**Issue by s12mmm3** [magic-akari/lrc-maker#140]
看源码外链为网易云的链接时会调用```https://music.163.com/song/media/outer/url?id=${id}.mp3```这个接口
![image](https://github.com/magic-akari/lrc-maker/assets/49340226/49385ecf-392c-4df6-a30b-71d4c5124bd6)
用postman调用发现，这个接口要求验证，因此获取不到音频资源
![image](https://github.com/magic-akari/lrc-maker/assets/49340226/7752cfdb-c055-4f50-a048-28bf92b68569)

**Comment by magic-akari** [comment]
没有找到这个歌曲。这个 id 指向的是你的云盘歌曲吗？

**Comment by s12mmm3** [comment]
😂贴错链接了```http://music.163.com/song/media/outer/url?id=2158256708.mp3```
![image](https://github.com/magic-akari/lrc-maker/assets/49340226/89ed2464-c657-4f8d-be67-9f0897884329)

**Comment by magic-akari** [comment]
工具里的 url 链接仅作有限支持。
通常情况下，需要浏览器可以直接访问播放的歌曲的链接。
对于云音乐的链接，会特殊处理一下，拼出你发现的那个链接，你可以尝试直接在浏览器里打开查看情况。

但是对于更加复杂的情况，工具不会尝试去解决，诸如版权问题，收费歌曲，又或者用户身处中国大陆之外而无法访问。
