### ISSUE TITLE
highlight current line on lyric content editor

### ISSUE THREAD

**Issue by Jonham** [magic-akari/lrc-maker#15]
hi, I found that difficult to recognize which line I am editing, maybe add a highlight effect to current line will be helpful ?

**Comment by magic-akari** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7829098/74581682-fafd4580-4fec-11ea-82c0-b1e7d1c69a79.png">

The highlighted line with the background color is the line being played.
The line with top and bottom borders and a time label is the line being edited.

If there is any problem, please let me know.

**Comment by Jonham** [comment]
mm, it works well on Synchronizer.

what I meant is on page [https://lrc-maker.github.io/#/editor/](https://lrc-maker.github.io/#/editor/) `difficult to recognize`.

**Comment by Jonham** [comment]
and I've try to add a highlight effect, but soon I realize that it's a `textarea` input box.
so it's not posibile to add any CSS at all.

try [React-Monaco](https://github.com/react-monaco-editor/react-monaco-editor) ?

**Comment by magic-akari** [comment]
It works as expected. There are currently no enhancement plans.

**Comment by Jonham** [comment]
ok.
