### ISSUE TITLE
音频网络请求错误

### ISSUE THREAD

**Issue by Rundong-Li** [magic-akari/lrc-maker#16]
通过外部链接导入的音频，导入成功后，播放到第2秒就显示音频网络请求错误，无法继续播放

**Comment by magic-akari** [comment]
能否提供一下音频链接？

**Comment by Rundong-Li** [comment]
> 能否提供一下音频链接？

https://music.163.com/#/song?id=1297532173
不止这一个，最近网易云的链接都有这个问题

**Comment by magic-akari** [comment]
我这边是正常播放的；你看一下是否开启了网络代理之类的。
网易云的链接是有一些限制的，比如，必须是非登陆态在 web 端能直接听的歌曲。

**Comment by Rundong-Li** [comment]
> 我这边是正常播放的；你看一下是否开启了网络代理之类的。
> 网易云的链接是有一些限制的，比如，必须是非登陆态在 web 端能直接听的歌曲。

我没有开代理，歌曲本身也没问题，可能是浏览器的问题？之前我一直用的chrome，没出现这个问题，刚刚换成firefox也是正常的。但是用Chrome的话还是有这个问题

**Comment by magic-akari** [comment]
用 Chrome 复现了。
可能是 Chrome 对权限要求比较严格。我的这个页面在 HTTPS 环境下，但是这个云音乐的外链重定向到了 HTTP 的链接。查看 console，发现 chrome 会尝试自动把重定向的链接再升级到 HTTPS。
至于为什么出错，这个问题比较难解。

**Comment by Rundong-Li** [comment]
好的，多谢。我还是老老实实换浏览器吧🤣
