### ISSUE TITLE
项目构建失败

### ISSUE THREAD

**Issue by yulintianxia** [magic-akari/lrc-maker#18]
![image](https://user-images.githubusercontent.com/44962371/80343769-0d231c00-8899-11ea-8f10-4b8a05197030.png)

**Comment by yulintianxia** [comment]
使用npm start时， 报错'make' 不是内部或外部命令，也不是可运行的程序
或批处理文件，

**Comment by magic-akari** [comment]
项目构建需要 make 工具等 *nix 环境。你可以尝试在 [WSL 环境](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install) 下或其他 *nix 环境下构建。
