### ISSUE TITLE
lrc-maker 4.0 roadmap

### ISSUE THREAD

**Issue by magic-akari** [magic-akari/lrc-maker#2]
## ESM

鉴于浏览器端 `JavaScript modules via script tag` (ESM) 逐步得到支持. 所以想试一试不打包源代码, 直接用浏览器加载模块.

## React

在 lrc-maker 2.0 的时候, 所用视图库由 React 切换到 preact , 其主要原因是

1.  当时没有找到 jsdelivr 这样好用的 CDN 服务, unpkg 在大陆地区访问困难, 所以选择连同库一起打包, 这样就对视图库的体积有所要求了.
2.  因为 GitHub 虽然能顺畅访问, 但是其缓存策略中, 缓存的时间很短, `max-age` 被设置为 600, 这意味着 10 分钟后, 缓存就会失效. 所以资源可能会被频繁下载, 需要对体积进行控制. (当然, 为后来使用了 service worker 来帮助缓存, 加快资源加载).

然而选择了 preact , 体积减小了, 但是也带来了很多问题, 比如[有些地方表现和 React 不一致](https://github.com/developit/preact/issues/940).

并且其他类 React 库已经跟不上 React 16 的新特性, 所以在 4.0 里边, React 将会被重新使用.

## [immer](https://github.com/mweststrate/immer)

lrc-maker 1.0 中, 使用的是手动管理 state, 在 2.0 之后, 使用 [MobX](https://github.com/mobxjs/mobx), 由于 MobX 过于灵活, 导致虽然整体 app 很高效, 但是数据流动是比较混乱的.
在 4.0 中将会使用 immer , 这相当于一个更加底层的 MobX, 并且 immer 可以和 Redux 一起使用.
但是不准备一开始就使用 Redux, React 16 中新增了 Context API, 如果这个 API 无法满足需求, 才会考虑引入 Redux.

## babel

在选择使用 preact 的时候, 由于仍然要使用 jsx 语法, 所以 babel 是必须的, 需要 `babel-plugin-transform-react-jsx` 这个插件来做语法转换.

在 4.0 中, 将会迁移到 Typescript , 由于 Typescript 内置了 jsx 转换, babel 不再是必须.
但这不意味着 babel 不会被使用, TypeScript 输出代码不支持压缩, 所以 babel-minify 将会被使用.

## webpack

不打包, 意味着不借助 webpack 也可以让 app 运行起来.
但是这不意味不使用 webpack 了, 因为仍然要对不支持 modules 的浏览器进行支持.

这里有个概念是 **渐进增强,优雅降级**.

这里可以把浏览器分成 3 类,

* 支持 `modules` 的浏览器
* 不支持 `modules`, 但对 ES6 支持良好的浏览器
* 支持 ES5 的浏览器

对于仅支持 ES5 的浏览器, 将会使用各种 polyfill, 并且不是维护的重点.

由于借助 webpack 实际上是可以分析模块的依赖关系的.
仅仅在 HTML 里包含入口文件, 让浏览器自动分析导入模块是可以的,
由于模块仅被加载一次, 并行加载以及延迟执行的特性, 我们将所有包都引入 HTML 理论上可以加快加载时间.

这里思路是

1.  使用 Typescript 将源码输出到临时目录, 例如 `tmp`
2.  由 webpack 打包, 通过插件 API 收集模块依赖关系, 按顺序写入 HTML 的 head 中.
3.  在步骤 2 中, 顺便调用 babel-minify, 将 Typescript 产生的文件压缩, 并输出.

## Typescript

目前 Typescript 中的 import 语句, 仅支持裸包名, 和后缀为 js 的包名, 并且输出时不会更改.
对于浏览器而言, 裸包名是不支持的, 那么只能选择 `import { Header } from 'Header.js'` 这种 import 语句.
然而, `Header.js` 并不真实存在, 存在的是 `Header.ts`.
Typescript 不会出错, 并且在浏览器里工作良好, 但是到了 webpack 里就会出错,

因为 webpack 找不到对应文件.

所以上边借助 tmp 目录中转, 而不直接使用 typescript 的 webpack loader 读取 ts 文件, 是一个妥协.
因为, typescript 编译后, `Header.ts` 会变成 `Header.js` 那么各种 import 语句将会变成合法的语句. webpack 也就能正常工作了.

PS. 理想的情况是, Typescript 支持 `import { Header } from 'Header.ts'` 这种语句, 并且在编译后会变成 `import { Header } from 'Header.js'`. 这样 webpack 的 loader 做相同的工作也很容易.

## Styled-Component

之前 CSS 的管理也是个难题. 在考虑几个方案后 Styled-Components 是比较理想的方案. 这个库会在运行时生成 css 并插入到 html 的 head 中.

CSS Modules 这种方案要求必须要有构建过程, 和我们路线相冲突, 所以无法采用. (我们路线中要求不依赖构建过程, 所使用的构建过程仅仅作为一种 fallback)

## node ESM

`node --experimental-modules` 以及 [ESM](https://github.com/standard-things/esm).

## wasm?

目前 app 中并没有什么 CPU 密集型运算, 最多也就是 lrc 的 序列化和反序列化过程. 但是这两个过程调用并不频繁, 所以使用 wasm 没有什么意义.

## 其他框架

* [stencil](https://github.com/ionic-team/stencil) 是一个很不错的框架, 但是其应用场景是一个大型的网站, 目前对 SPA 支持并不友好.
* Vue 很棒, 但是我已经使用 React 了.
* [lit-html](https://github.com/Polymer/lit-html) 太轻量了. 但是这是一个很不错的库, 让我产生了写一个 lit-jsx 的想法.(运行时 parse jsx, 回归 javascript, 不用 babel 也不用 Typescript) 但是目前能力不够, 而且考虑到 parse 过程可能对性能也有损失.

**Comment by hufan-akari** [comment]
webpack 插件示例代码
```js
import { transformFile as _transformFile } from "@babel/core";
import { basename, posix, resolve } from "path";
import { promisify } from "util";

const transformFile = promisify(_transformFile);

const pluginName = "MyWebpackPlugin";

export class MyWebpackPlugin {
  /**
   * constructor
   * @param {object} options
   * @param {string} options.basePath
   * @param {RegExp} options.filter
   */
  constructor(options) {
    const { basePath, filter } = options;
    this.basePath = basePath;
    this.filter = filter;
    this.sourceList = [];
  }

  apply(compiler) {
    compiler.hooks.normalModuleFactory.tap(
      pluginName,
      this.onNormalModuleFactory.bind(this)
    );
    compiler.hooks.emit.tapPromise(pluginName, this.onEmit.bind(this));
  }

  onNormalModuleFactory(compiler) {
    compiler.hooks.beforeResolve.tap(
      pluginName,
      this.onBeforeResolve.bind(this)
    );
  }

  onBeforeResolve(request) {
    const abslotePath = resolve(request.context, request.request);
    if (this.filter.test(abslotePath)) {
      let relativePath = posix.relative(this.basePath, abslotePath);

      this.sourceList.unshift({ relativePath, abslotePath });
    }
  }

  onEmit(compilation) {
    return Promise.all(
      this.sourceList.map(async ({ relativePath, abslotePath }) => {
        const { code, map } = await transformFile(abslotePath, {
          presets: ["minify"],
          sourceMaps: true
        });

        const codePath = relativePath;
        const mapPath = `${relativePath}.map`;
        const mapName = basename(mapPath);
        const codeContent = `${code}\n//# sourceMappingURL=${mapName}`;

        const mapContent = JSON.stringify(map);

        compilation.assets[codePath] = {
          source: () => {
            return codeContent;
          },
          size: () => {
            return codeContent.length;
          }
        };
        compilation.assets[mapPath] = {
          source: () => {
            return mapContent;
          },
          size: () => {
            return mapContent.length;
          }
        };

        return relativePath;
      })
    ).then(esmFiles => {
      // 进行预渲染, 写入 esmFiles 到 html 的 head 中
    });
  }
}
```

**Comment by hufan-akari** [comment]
其实我们可以不借助 webpack 来找到所有的 `.ts` 文件。
直接通过 cli 来转换 src 中所有的 `.ts` 文件。
我们在源码种书写

```js
import { Header } from 'Header'
```

并试图在输出的时候修改这个 import 语句。
这是 babel 插件的写法。

`babel-plugin/add-import-js-extension.js`

```js
"use strict";

module.exports = function() {
  return {
    visitor: {
      ImportDeclaration: function(path) {
        let source = path.node.source;

        if (!source.value.endsWith(".js")) {
          source.value += ".js";
        }
      },
    },
  };
};
```

`.babelrc`

```json
{
  "presets": ["babel-preset-minify"],
  "plugins": [
    "./babel-plugin/add-import-js-extension.js"
  ]
}
```

---

除此之外，如果 TypeScript 直接支持在输出文件的 import 语句补上 `.js` 后缀。
那么我们就不再需要 babel 来做转换，
由于 http/2 和 gzip 等技术，minify 压缩也不是必要的。
这需要等待 https://github.com/Microsoft/TypeScript/pull/25073 合入 TypeScript 项目。
这样,直接使用命令行 `tsc` 就可以构建项目，而不依赖 webpack/babel 。

**Comment by hufan-akari** [comment]
[lit-element](https://github.com/Polymer/lit-element) 也是一个备选方案。这是一个基于 lit-html 封装成的 view 库。同时这是 Polymer 衍生出来的类库。

期待 Polymer 能够推动 web components 发展，让浏览器原生组件更好用。
这样以后直接使用浏览器原生组件，旧浏览器只要打上 polyfill 就可以了。

鉴于不满前端现状，此项目可能需要搁置一段时间，观察 web 开发环境的发展。

**Comment by hufan-akari** [comment]
Todo:
- [ ] 支持保存歌词到 Github Gist
- [ ] 支持时间轴整体偏移
- [ ] 支持 ncm 格式

**Comment by magic-akari** [comment]
- [ ] 更换为 MIT 许可证

**Comment by magic-akari** [comment]
5.0 已完成。
