### ISSUE TITLE
新特性

### ISSUE THREAD

**Issue by ritaswc** [magic-akari/lrc-maker#20]
同步歌词格式是支持同一歌词行合并的
比如：
```
[00:01:23]我是卖报的小行家
[00:02:13]我是卖报的小行家
```
可以合并成为
```
[00:01:23][00:02:13]我是卖报的小行家
```
希望作者在下载lrc歌词的时候支持这个特性
当然，如果在软件核心中，支持这种合并格式那是再好不过了

**Comment by magic-akari** [comment]
在实用工具里支持转换了（编辑模式右上角）。如果看不到，可以在设置里清一下缓存。
因为歌词滚动姬对歌词文本的线性顺序严格依赖，所以核心还是不支持的。
