### ISSUE TITLE
本地化请求

### ISSUE THREAD

**Issue by unbadfish** [magic-akari/lrc-maker#21]
如题，请求一个本地化的版本，比方说点击`index.html`就能在浏览器里用的版本

**Comment by unbadfish** [comment]
#18

**Comment by magic-akari** [comment]
请问，你的需求是否是“离线可访问”？

**Comment by unbadfish** [comment]
是。
node.js总是失败，就和#18一样



---原始邮件---
发件人: "阿卡琳"<notifications@github.com&gt;
发送时间: 2020年6月11日(周四) 中午12:36
收件人: "magic-akari/lrc-maker"<lrc-maker@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"unbadfish"<3066893506@qq.com&gt;;
主题: Re: [magic-akari/lrc-maker] 本地化请求 (#21)




 
请问，你的需求是否是“离线可访问”？

**Comment by magic-akari** [comment]
线上页面是有离线访问能力的。使用 Chrome 浏览器（或者其他支持 PWA 的浏览器），在访问一次（可能是两次）页面后，你可以尝试断网再访问。

你也可以把它安装到本地，只需要点击 Chrome 地址栏旁边的 "+" 号按钮。
<img width="354" alt="image" src="https://user-images.githubusercontent.com/7829098/84346891-a73dea00-abe3-11ea-904e-cf16496634d4.png">

或者在右上角三个点菜单里也有。
<img width="370" alt="image" src="https://user-images.githubusercontent.com/7829098/84346977-eb30ef00-abe3-11ea-8d39-32f574d4f97a.png">

**Comment by unbadfish** [comment]
谢谢，现在有事，下午试一下。



---原始邮件---
发件人: "阿卡琳"<notifications@github.com&gt;
发送时间: 2020年6月11日(周四) 中午1:04
收件人: "magic-akari/lrc-maker"<lrc-maker@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"unbadfish"<3066893506@qq.com&gt;;
主题: Re: [magic-akari/lrc-maker] 本地化请求 (#21)




 
线上页面是有离线访问能力的。使用 Chrome 浏览器（或者其他支持 PWA 的浏览器），在访问一次（可能是两次）页面后，你可以尝试断网再访问。
 
你也可以把它安装到本地，只需要点击 Chrome 地址栏旁边的 "+" 号按钮。
 
 
或者在右上角三个点菜单里也有。

**Comment by unbadfish** [comment]
谢谢，用的是firefox，看了[这篇文章](https://geekermag.com/enable-site-specific-browser-firefox/)，会用了。
建议修改readme
还是有个问题：App mode 下点击下载![图片](https://user-images.githubusercontent.com/61961263/84365483-1c211c00-ac04-11ea-93bd-cdce3944c628.png)只能在新窗口弹出lrc格式的文本，不能下载，建议增加一个直接保存到MP3所在文件夹的功能

**Comment by unbadfish** [comment]
建议再增加一个清空全部数据（文本和音频）的功能
