### ISSUE TITLE
清除缓存导致网络无法连接

### ISSUE THREAD

**Issue by unbadfish** [magic-akari/lrc-maker#25]
电脑端点击清除缓存后无法访问*所有*的http**s**://xx.gitgub.io页面，但github访问正常
用Python进行get，结果显示` WinError 10061`
手机测试结果相同（无法访问）
请问这是为什么？出了什么问题？应该如何补救？

**Comment by magic-akari** [comment]
中国特色网络问题，没有什么特别的补救方法。
如果你连上了互联网，可以使用 [Chrome 的“添加到桌面”功能](https://sspai.com/post/43499)强制缓存页面，这样可以无视网络情况离线使用。

**Comment by unbadfish** [comment]
但是……错误码和访问被墙页面的错误码不一样
lrc-maker:`[WinError 10061] 由于目标计算机积极拒绝，无法连接。`
google:`[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。`
以我的理解，这两个错误好像不一样……

**Comment by magic-akari** [comment]
要判断网络错误背后发生了什么，需要更多的专业知识和经验。
有可能以后 GitHub Page 可能会像 Github Gist 一样在一些地区访问困难直至完全无法访问。
但是我并不太想深究网络质量的问题，因为我没有能力对现状做出什么改变。
这个页面托管在 GitHub Page 上，是众多 GitHub Page 托管页面之一，我相信只要 GitHub 依然提供服务，它本身是没有什么问题的。

本项目实质是提供了源代码，而托管的页面只是利用了 GitHub 免费资源之便。作为开源项目作者，我也无法要求或者承担这项免费服务的质量或稳定性。

**Comment by unbadfish** [comment]
谢谢



---原始邮件---
发件人: "阿卡琳"<notifications@github.com&gt;
发送时间: 2020年10月5日(周一) 晚上10:34
收件人: "magic-akari/lrc-maker"<lrc-maker@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"unbadfish"<3066893506@qq.com&gt;;
主题: Re: [magic-akari/lrc-maker] 清除缓存导致网络无法连接 (#25)




 
要判断网络错误背后发生了什么，需要更多的专业知识和经验。
 有可能以后 GitHub Page 可能会像 Github Gist 一样在一些地区访问困难直至完全无法访问。
 但是我并不太想深究网络质量的问题，因为我没有能力对现状做出什么改变。
 这个页面托管在 GitHub Page 上，是众多 GitHub Page 托管页面之一，我相信只要 GitHub 依然提供服务，它本身是没有什么问题的。
 
本项目实质是提供了源代码，而托管的页面只是利用了 GitHub 免费资源之便。作为开源项目作者，我也无法要求或者承担这项免费服务的质量或稳定性。

**Comment by magic-akari** [comment]
这里还有个[备用地址](https://lrc-maker.vercel.app)，虽然这并没有解决问题。

**Comment by unbadfish** [comment]
神奇的是它解决了问题:joy:

**Comment by magic-akari** [comment]
这个地址会作为开发分支使用（它可能比部署到 https://lrc-maker.github.io 的版本更新）。
但是这也是一项免费的服务，如果它被广泛滥用，那么在不久后同样会访问困难。
