### ISSUE TITLE
感谢作者编写的这个工具,基本完美满足了我的要求.

### ISSUE THREAD

**Issue by yyancy** [magic-akari/lrc-maker#29]

**Comment by magic-akari** [comment]
抱歉回复这么晚。请问您的问题是否已经解决了？

**Comment by yyancy** [comment]
嗯,问题解决了.工具很好用.
感谢回复!

**Comment by yyancy** [comment]
感谢




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2020年12月7日(星期一) 下午5:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [magic-akari/lrc-maker] 感谢作者编写的这个工具,基本完美满足了我的要求. (#29)





 
抱歉回复这么晚。请问您的问题是否已经解决了？
