### ISSUE TITLE
希望能添加时间轴微调按钮

### ISSUE THREAD

**Issue by WXRIW** [magic-akari/lrc-maker#39]
真的好用，第一次使用只花了几分钟就会了！
如图，Musixmatch的歌词制作是可以微调时间轴的，这对于有些不太好卡点的歌会很方便，先完整打出整体时间轴，再逐句微调。
![image](https://user-images.githubusercontent.com/62491584/127443473-4c44ab53-75fe-4221-877d-9c72aa830d02.png)
解释下图上的按钮：
最左边的X是删除这一个时间轴
右边一点的-和+是以250ms为单位进行微调，并且微调的时候会自动从这个新的进度开始播放，很方便就知道是否卡上了！
播放按钮是直接从当前句播放。

工具很好用，感谢开发者！

**Comment by WXRIW** [comment]
我个人的建议是250ms仍然较大，可改为150ms

**Comment by unbadfish** [comment]
建议用`z`和`x`键进行微调，ad键跳时间，搭配着用
