### ISSUE TITLE
阿卡琳快出来出来看看你的porn（划掉）github！我要调音量的

### ISSUE THREAD

**Issue by FinaFina233** [magic-akari/lrc-maker#42]
默认好大声啊，虽然说可以系统音量但是好麻烦的说。。每次还要调回去

**Comment by magic-akari** [comment]
请使用 [3.x 版本](https://lrc-maker.github.io/3.x/)

**Comment by magic-akari** [comment]
还有另一种解法：设置里，切换到浏览器内置音频播放器，一般内置播放器的界面都是有音量调节的。
