### ISSUE TITLE
[Feature request] Docker image

### ISSUE THREAD

**Issue by Pheggas** [magic-akari/lrc-maker#48]
Hello and thank you very much for this project! Really saved me a lot of time! Anyway, i'd like to ask if you're willing to put whole LRC Maker into docker image so anyone can put it on it's server for example and don't need painfully search for your github.io web.

**Comment by magic-akari** [comment]
Sorry for late response.
This is a good idea. But I'm not familiar to Docker.
A pull request is welcome.
