### ISSUE TITLE
对Firefox的适配似乎存在问题

### ISSUE THREAD

**Issue by DeepChirp** [magic-akari/lrc-maker#95]
Firefox版本：119.0.1 (64 位)
Windows版本：23H2 (OS内部版本 22631.2715)
歌词滚动姬版本：
* 稳定版：5.6.9 (Commit hash `60e4d91`)
* 开发分支版：5.6.9 (Commit hash `8ec0108`)

感谢作者开发了如此好用的工具。然而该工具似乎没有完全适配Firefox。

在已经禁用所有扩展的情况下，有问题的页面如下：
1. 歌词编辑页面的文本框高度过小，如下图
![图片](https://github.com/magic-akari/lrc-maker/assets/66902050/8627e105-07e9-4b29-b98c-777cf51f11f2)

2. 疑似无法正常打轴，在打轴页面按下空格时，页面向下滚动，歌词前没有添加时间轴，如下图
![2023-11-20 092840](https://github.com/magic-akari/lrc-maker/assets/66902050/422b19dd-4c00-4076-94cf-2e4fa36a8979)

希望作者能够解决一下。非常感谢！

**Comment by magic-akari** [comment]
看起来是 lightningcss(4d9289464155b18d2eba96d77fd28dc1bb1552e6) 引入的问题。
你能否尝试一下这个链接是否正常 https://lrc-maker-git-fork-lkho-feature-build-docker-image-magic-akari.vercel.app/#/

**Comment by DeepChirp** [comment]
> 看起来是 lightningcss([4d92894](https://github.com/magic-akari/lrc-maker/commit/4d9289464155b18d2eba96d77fd28dc1bb1552e6)) 引入的问题。 你能否尝试一下这个链接是否正常 https://lrc-maker-git-fork-lkho-feature-build-docker-image-magic-akari.vercel.app/#/

该页面是正常的，两个问题均没有再复现
